In [1]:
import numpy as np
import statistics as sts

In [21]:
import pandas as pd

In [2]:
n = np.random.randn(30)

In [3]:
n.shape

(30,)

In [4]:
n.ndim

1

In [5]:
n

array([-5.79609340e-01, -1.46496584e+00,  5.01039543e-01, -6.13063507e-01,
       -3.72737967e-01, -4.80878180e-01, -6.18802589e-01, -1.02529393e+00,
       -5.20387682e-01,  7.98402313e-01,  5.53865744e-01, -4.69950864e-01,
        5.06070250e-01,  1.98245085e-01, -3.92007423e-01, -2.10273014e+00,
       -1.15635671e+00, -2.89387696e-01,  8.12003138e-01,  1.08547074e+00,
        2.17109924e-01,  3.23090353e-01,  1.59332005e+00, -4.13797592e-03,
       -9.60750322e-01,  1.14879261e-03, -1.22723615e+00, -1.34310220e+00,
        4.51167116e-01, -1.57723901e-01])

In [6]:
np.max(n)

1.5933200497091757

In [7]:
np.min(n)

-2.10273014020676

In [8]:
np.median(n)

-0.33106283142165344

In [9]:
np.mean(n)

-0.22460631195513106

In [10]:
n2 = np.random.randint(5,20,11)

In [11]:
n2

array([17,  6, 14, 16, 17, 10,  7, 14,  6,  5, 15])

In [12]:
np.mean(n2)

11.545454545454545

In [13]:
np.median(n2)

14.0

In [14]:
np.max(n2)

17

In [15]:
np.min(n2)

5

In [16]:
sts.median_high(n2)

14

In [17]:
np.median(n2)

14.0

In [18]:
n2

array([17,  6, 14, 16, 17, 10,  7, 14,  6,  5, 15])

In [19]:
result = np.max(n2) - np.min(n2)

In [20]:
result

12

In [22]:
df = n2

In [23]:
n2

array([17,  6, 14, 16, 17, 10,  7, 14,  6,  5, 15])

In [24]:
df.sort()

In [25]:
df

array([ 5,  6,  6,  7, 10, 14, 14, 15, 16, 17, 17])

In [26]:
n2

array([ 5,  6,  6,  7, 10, 14, 14, 15, 16, 17, 17])

In [27]:
np.flipud(df)

array([17, 17, 16, 15, 14, 14, 10,  7,  6,  6,  5])

In [28]:
q1=np.percentile(n2,25)
q1

6.5

In [29]:
q2 = np.percentile(n2,50)
q2

14.0

In [30]:
q3 = np.percentile(n2,75)
q3

15.5

In [31]:
p1 = sts.median_high(n2)
p1

14

In [32]:
p2 = q3-q1
p2

9.0

In [33]:
n

array([-5.79609340e-01, -1.46496584e+00,  5.01039543e-01, -6.13063507e-01,
       -3.72737967e-01, -4.80878180e-01, -6.18802589e-01, -1.02529393e+00,
       -5.20387682e-01,  7.98402313e-01,  5.53865744e-01, -4.69950864e-01,
        5.06070250e-01,  1.98245085e-01, -3.92007423e-01, -2.10273014e+00,
       -1.15635671e+00, -2.89387696e-01,  8.12003138e-01,  1.08547074e+00,
        2.17109924e-01,  3.23090353e-01,  1.59332005e+00, -4.13797592e-03,
       -9.60750322e-01,  1.14879261e-03, -1.22723615e+00, -1.34310220e+00,
        4.51167116e-01, -1.57723901e-01])

In [34]:
n_sample = np.random.choice(n,20)
n_sample

array([-1.02529393, -0.1577239 ,  0.55386574,  0.81200314, -2.10273014,
       -0.1577239 , -0.61306351, -1.22723615,  1.08547074, -0.46995086,
       -1.46496584, -0.1577239 , -1.3431022 , -1.15635671,  0.32309035,
        0.32309035,  0.50103954, -0.00413798,  0.19824509, -0.46995086])

In [35]:
n_result=np.var(n)
n_result

0.670549301813857

In [36]:
n_result_Sample = np.var(n_sample)
n_result_Sample

0.6827254616044951

In [37]:
df.std()

4.5798697155672725

In [39]:
print("Hello World",n)

Hello World [-5.79609340e-01 -1.46496584e+00  5.01039543e-01 -6.13063507e-01
 -3.72737967e-01 -4.80878180e-01 -6.18802589e-01 -1.02529393e+00
 -5.20387682e-01  7.98402313e-01  5.53865744e-01 -4.69950864e-01
  5.06070250e-01  1.98245085e-01 -3.92007423e-01 -2.10273014e+00
 -1.15635671e+00 -2.89387696e-01  8.12003138e-01  1.08547074e+00
  2.17109924e-01  3.23090353e-01  1.59332005e+00 -4.13797592e-03
 -9.60750322e-01  1.14879261e-03 -1.22723615e+00 -1.34310220e+00
  4.51167116e-01 -1.57723901e-01]


In [40]:
sum(n)

-6.738189358653931

In [41]:
len(n)

30

In [46]:
np.mean(n)

-0.22460631195513106

In [61]:
np.std(n)

0.8188707479290349

## Add a link in jupyter notebook
First Set this column as a Markdown.Then Write Name of your link in Third Bracket [ ] . Then paste your url link in First Bracket( ).

ex.

    [DataSet](https://www.kaggle.com/alexisbcook/titanic-tutorial)

# Some Tecnique
The variables `cost_of_ice_bag`, `profit_margin`, and `number_of_bags` now contain the information provided in the word problem. We can check the value of a variable by typing its name into a cell. We can combine variables using arithmetic operations to create other variables.

> **Code completion**: While typing the name of an existing variable in a code cell within Jupyter, just type the first few characters and press the `Tab` key to autocomplete the variable's name. Try typing `pro` in a code cell below and press `Tab` to autocomplete to `profit_margin`.

| Operator  | Purpose          | Example    | Result |
|-----------|------------------|------------|--------|
| `+`       | Addition         | `2 + 3`    | `5`    |
| `-`       | Substraction     | `3 - 2`    | `1`    |
| `*`       | Multiplication   | `8 * 12`   | `96`   |
| `/`       | Division         | `100 / 7`  | `14.28`|
| `//`      | Floor Division   | `100 / 7`  | `14`   |
| `%`       | Modilus/Reminder | `100 % 7`  | `2`    |
| `**`      | Exponent         | `5 ** 3`   | `125`  |

*hello* **world**

ModuleNotFoundError: No module named 'dataframe'

In [75]:
n

array([-5.79609340e-01, -1.46496584e+00,  5.01039543e-01, -6.13063507e-01,
       -3.72737967e-01, -4.80878180e-01, -6.18802589e-01, -1.02529393e+00,
       -5.20387682e-01,  7.98402313e-01,  5.53865744e-01, -4.69950864e-01,
        5.06070250e-01,  1.98245085e-01, -3.92007423e-01, -2.10273014e+00,
       -1.15635671e+00, -2.89387696e-01,  8.12003138e-01,  1.08547074e+00,
        2.17109924e-01,  3.23090353e-01,  1.59332005e+00, -4.13797592e-03,
       -9.60750322e-01,  1.14879261e-03, -1.22723615e+00, -1.34310220e+00,
        4.51167116e-01, -1.57723901e-01])

In [76]:
list(n)

[-0.579609340280897,
 -1.4649658414640767,
 0.5010395432175452,
 -0.6130635074989873,
 -0.37273796716261054,
 -0.4808781798554428,
 -0.6188025892631532,
 -1.0252939252441857,
 -0.5203876815952352,
 0.7984023134015421,
 0.5538657438741817,
 -0.46995086421121307,
 0.5060702502039544,
 0.1982450854647243,
 -0.39200742299718144,
 -2.10273014020676,
 -1.1563567137845934,
 -0.28938769568069633,
 0.8120031376215991,
 1.0854707440212998,
 0.21710992380186364,
 0.323090353226439,
 1.5933200497091757,
 -0.004137975916805172,
 -0.9607503215834284,
 0.0011487926081497118,
 -1.2272361488735453,
 -1.3431021951038786,
 0.4511671155499816,
 -0.15772390063169758]

In [85]:
type(n)

numpy.ndarray

In [90]:
df =pd.DataFrame(n)

In [95]:
df.values.flatten()

array([-5.79609340e-01, -1.46496584e+00,  5.01039543e-01, -6.13063507e-01,
       -3.72737967e-01, -4.80878180e-01, -6.18802589e-01, -1.02529393e+00,
       -5.20387682e-01,  7.98402313e-01,  5.53865744e-01, -4.69950864e-01,
        5.06070250e-01,  1.98245085e-01, -3.92007423e-01, -2.10273014e+00,
       -1.15635671e+00, -2.89387696e-01,  8.12003138e-01,  1.08547074e+00,
        2.17109924e-01,  3.23090353e-01,  1.59332005e+00, -4.13797592e-03,
       -9.60750322e-01,  1.14879261e-03, -1.22723615e+00, -1.34310220e+00,
        4.51167116e-01, -1.57723901e-01])

In [99]:
count = (n < 0 ).sum().sum()
count

18

In [84]:
n1 = abs(n)
list(n1)

[0.579609340280897,
 1.4649658414640767,
 0.5010395432175452,
 0.6130635074989873,
 0.37273796716261054,
 0.4808781798554428,
 0.6188025892631532,
 1.0252939252441857,
 0.5203876815952352,
 0.7984023134015421,
 0.5538657438741817,
 0.46995086421121307,
 0.5060702502039544,
 0.1982450854647243,
 0.39200742299718144,
 2.10273014020676,
 1.1563567137845934,
 0.28938769568069633,
 0.8120031376215991,
 1.0854707440212998,
 0.21710992380186364,
 0.323090353226439,
 1.5933200497091757,
 0.004137975916805172,
 0.9607503215834284,
 0.0011487926081497118,
 1.2272361488735453,
 1.3431021951038786,
 0.4511671155499816,
 0.15772390063169758]

In [71]:
a = int(input())
if(a > 0):
    print("Positive Number")
else:
    print("Negetive Number")

-9
Negetive Number


In [73]:
import math as mt

In [74]:
mt.pi

3.141592653589793

In [102]:
today = "Tuesday"

In [103]:
today[0]

'T'

In [104]:
n[19]

1.0854707440212998

In [105]:
n[10 : 13]

array([ 0.55386574, -0.46995086,  0.50607025])

In [106]:
a = "Hello"
b = "World"

In [113]:
a.lower() +" "  + b.upper() + "!"

'hello WORLD!'

In [115]:
a[0:2] + " " + b[2:5]

'He rld'

In [122]:
p = " I had got GPA = {} in exam."
s = int(input())
print(p.format(s))

8
 I had got GPA = 8 in exam


In [126]:
list(n)

[-0.579609340280897,
 -1.4649658414640767,
 0.5010395432175452,
 -0.6130635074989873,
 -0.37273796716261054,
 -0.4808781798554428,
 -0.6188025892631532,
 -1.0252939252441857,
 -0.5203876815952352,
 0.7984023134015421,
 0.5538657438741817,
 -0.46995086421121307,
 0.5060702502039544,
 0.1982450854647243,
 -0.39200742299718144,
 -2.10273014020676,
 -1.1563567137845934,
 -0.28938769568069633,
 0.8120031376215991,
 1.0854707440212998,
 0.21710992380186364,
 0.323090353226439,
 1.5933200497091757,
 -0.004137975916805172,
 -0.9607503215834284,
 0.0011487926081497118,
 -1.2272361488735453,
 -1.3431021951038786,
 0.4511671155499816,
 -0.15772390063169758]

In [125]:
n[:5]

array([-0.57960934, -1.46496584,  0.50103954, -0.61306351, -0.37273797])

In [146]:
def personal(Me):
    
    """'Name': Me
    'Age': 18
    'Passed Study': ' HSC'
    'Current Studying': 'BSc' """

In [147]:
print(personal('Shuvo'))

None


In [1]:
def personal1(Me):
    print("")


In [2]:
import git

ModuleNotFoundError: No module named 'git'